# Generated by Django 4.2 on 2023-04-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_video_preview_alter_video_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
