# Generated by Django 4.2 on 2023-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(blank=True, default='preview/nopreview.jpg', null=True, upload_to='preview/', verbose_name='Превью'),
        ),
    ]
